package com.valtech.azubi.bankanwendung.model.core;

public enum AktionsTyp {
KUNDE_ANGELEGT,KUNDE_GELÖSCHT,KONTO_ANGELEGT,KONTO_GESPERRT,KONTO_SPERRE_AUFGEHOBEN,DISPO_FESTGELEGT,PIN_ZURÜCKGESETZT,DATEN_GEÄNDERT
}